# pip install pre-commit
# pre-commit install
# pre-commit run --all-files
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/python/black.git
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python
  - repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
        language_version: python
