apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.name | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - python
    - fastapi
    - openapi
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: ./api/openapi.yaml
