version: '2'
services:

  app:
    build: .
    ports:
      - ${PORT:-8000}:8000
    restart: always
    environment:
      PORT: 8000
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
