pipeline:
  identifier: Build_shahabdullah1989_harness_coding_assignment_1759522314193
  name: Build harness-coding-assignment
  orgIdentifier: default
  projectIdentifier: Coding_Assessment
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: shahabdullah1989/harness-coding-assignment
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    connectorRef: shahdocker
                    image: python:3.10.10
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Install dependencies and Build Python Code
                  identifier: Run_2
                  spec:
                    connectorRef: shahdocker
                    image: python:3.10.10
                    shell: Sh
                    command: |-
                      python -m venv venv 
                      /bin/bash ./venv/bin/activate
                      pip install -r requirements.txt
                      pip install uvicorn
                      pip list
                      python src/server.py
                      sigkill
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8s_local
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
